CREATE TABLE CLIENTE_TB(
	ID INTEGER IDENTITY(1,1),
	CODIGOCLIENTE NVARCHAR(15),
	NOME VARCHAR(100),
	SOBRENOME VARCHAR(50),
	SEXO CHAR(1),
	DATANASC DATE,
	CPF VARCHAR(11),
	EMAIL VARCHAR(80),
	TELEFONE VARCHAR(11),
	CONSTRAINT PK_CLIENTE PRIMARY KEY(ID)
)
GO
--CODIGO DO CLIENTE É A REFERENCIA DAS 4 PRIMEIRAS LETRAS DO NOME MAIS O CPF

CREATE TABLE CLIENTEACESSO_TB(
	CODIGOCLIENTE NVARCHAR(15),
	CPF VARCHAR(11),
	EMAIL VARCHAR(80),
	SENHA VARCHAR(6)
)
GO
--PODEREMOS CRIAR UMA ROTINA, QUANDO EU INSERIR UM CLIENTE, ATRAVÉS DO GATILHO ELE CRIE OS DADOS DESTA TABELA

CREATE TABLE MARCA(
	ID INTEGER IDENTITY,
	NOMEMARCA VARCHAR(100)
	CONSTRAINT PK_MARCA PRIMARY KEY(ID)
)
GO

CREATE TABLE TIPOPRODUTO(
	ID INTEGER IDENTITY,
	NOMETIPOPRODUTO VARCHAR(100),
	CONSTRAINT PK_TIPOPRODUTO PRIMARY KEY(ID)
)
GO

CREATE TABLE PRODUTO
(
	ID INTEGER IDENTITY(1,1),
	CODIGOPRODUTO INTEGER,
	NOMEPRODUTO VARCHAR(100),
	VALORUNITARIO DECIMAL(10,2) NULL,
	IDMARCA INTEGER,
	IDTIPOPRODUTO INTEGER
	CONSTRAINT PK_PRODUTO PRIMARY KEY(ID),
	CONSTRAINT FK_PRODUTOMARCA FOREIGN KEY(IDMARCA) REFERENCES MARCA(ID),
	CONSTRAINT FK_PRODUTOTIPO FOREIGN KEY(IDTIPOPRODUTO) REFERENCES TIPOPRODUTO(ID)
)
GO
--CODIGO DO PRODUTO É A REFERENCIA DAS DO IDMARCA MAIS O IDTIPOPRODUTO

