SELECT * FROM ESPECIALIDADE_TB;
SELECT * FROM MEDICO_TB;
SELECT * FROM PACIENTE_TB;
SELECT * FROM CONSULTA_TB;
SELECT * FROM PAGAMENTO_TB;

--SELECIONAR QUAL A ESPECIALIDADE DO MEDICO E SEU NOME, E CRM 
SELECT ESPECIALIDADE_TB.NOME, MEDICO_TB.NOME, MEDICO_TB.CRM FROM 
	ESPECIALIDADE_TB 
	INNER JOIN MEDICO_TB
	ON ESPECIALIDADE_TB.ID = MEDICO_TB.ID_ESPECIALIDADE

--SELECIONAR QUAL A O PACIENTE, QUAL MEDICO E ESPECIALIDADE O PACIENTE PASSOU EM CONSULTA E 
--QUAL FOI O DIA E HORA DA CONSULTA
SELECT PACIENTE_TB.NOME, MEDICO_TB.NOME, ESPECIALIDADE_TB.NOME, 
       CONSULTA_TB.DATA_CONSULTA, CONSULTA_TB.HORA_CONSULTA 
FROM 
	PACIENTE_TB
	INNER JOIN CONSULTA_TB
	ON PACIENTE_TB.ID = CONSULTA_TB.ID_PACIENTE
	INNER JOIN MEDICO_TB
	ON CONSULTA_TB.ID_MEDICO = MEDICO_TB.ID
	INNER JOIN ESPECIALIDADE_TB
	ON MEDICO_TB.ID_ESPECIALIDADE = ESPECIALIDADE_TB.ID
WHERE CONSULTA_TB.DATA_CONSULTA <= GETDATE() -1

--SELECIONAR QUAL A O PACIENTE, QUAL MEDICO E ESPECIALIDADE O PACIENTE PASSOU EM CONSULTA E QUAL SERÁ O DIA E HORA DA CONSULTA
SELECT PACIENTE_TB.NOME, MEDICO_TB.NOME, ESPECIALIDADE_TB.NOME, CONSULTA_TB.DATA_CONSULTA, CONSULTA_TB.HORA_CONSULTA FROM 
	PACIENTE_TB
	INNER JOIN CONSULTA_TB
	ON PACIENTE_TB.ID = CONSULTA_TB.ID_PACIENTE
	INNER JOIN MEDICO_TB
	ON CONSULTA_TB.ID_MEDICO = MEDICO_TB.ID
	INNER JOIN ESPECIALIDADE_TB
	ON MEDICO_TB.ID_ESPECIALIDADE = ESPECIALIDADE_TB.ID
WHERE CONSULTA_TB.DATA_CONSULTA > GETDATE()

--MOSTRAR AS CONSULTAS PAGAS E O TIPO DE PAGAMENTO
SELECT PAGAMENTO_TB.TIPO_PAGAMENTO, CONSULTA_TB.* FROM 
	PAGAMENTO_TB
	INNER JOIN CONSULTA_TB
	ON PAGAMENTO_TB.ID_CONSULTA = CONSULTA_TB.ID

--MOSTRAR OS PAGAMENTOS DO MES ATUAL
SELECT SUM(PAGAMENTO_TB.AVISTA) AVISTA, SUM(PAGAMENTO_TB.PARCELADO) PARCELADO FROM 
	PAGAMENTO_TB
	INNER JOIN CONSULTA_TB
	ON PAGAMENTO_TB.ID_CONSULTA = CONSULTA_TB.ID
	WHERE (CONSULTA_TB.DATA_CONSULTA >= '2018-07-01'
	  AND CONSULTA_TB.DATA_CONSULTA <= '2018-07-31')

--MESMA CONSULTA DE CIMA USANDO O BETWEEN
SELECT SUM(PAGAMENTO_TB.AVISTA) AVISTA, SUM(PAGAMENTO_TB.PARCELADO) PARCELADO
	FROM 
	PAGAMENTO_TB
	INNER JOIN CONSULTA_TB
	ON PAGAMENTO_TB.ID_CONSULTA = CONSULTA_TB.ID
	WHERE CONSULTA_TB.DATA_CONSULTA BETWEEN '2018-07-01' AND '2018-07-31'

