CREATE PROCEDURE PROC_ESPECIALIDADE_I(@ID INTEGER, @NOME VARCHAR)
AS

BEGIN
	INSERT INTO ESPECIALIDADE_TB(ID, NOME)
	VALUES(@ID, @NOME);
	PRINT 'INCLUIDO COM SUCESSO'
END;


EXEC PROC_ESPECIALIDADE_I @ID = 5, @NOME = 'PSIQUIATRA'



CREATE PROCEDURE PROC_ESPECIALIDADE_U(@ID INTEGER, @NOME VARCHAR)
AS

IF @ID != NULL
	
	BEGIN
		UPDATE ESPECIALIDADE_TB
		SET NOME = @NOME
		WHERE ID = @ID
		PRINT 'ALTERADO COM SUCESSO'
	END;
ELSE 
	BEGIN
		PRINT 'ERRO FATAL'
	END	
END

EXEC PROC_ESPECIALIDADE_U

CREATE PROCEDURE PROC_ESPECIALIDADE_S
AS

BEGIN
	SELECT * FROM ESPECIALIDADE_TB
END 

EXEC PROC_ESPECIALIDADE_S

